<?php
    //nobl/newproducts/newproducts.phtml

    /*
        Returns an array containing values from the module
        section in the admin as defined by system.xml
    */
    $config = Mage::getStoreconfig('newproducts');          

    // get product_limit/products value
    $limit = $config['product_limit']['products'];

    //echo "<p>Product Limit: {$limit}";


    //echo "<p>New Product Values:";
    //var_dump($config['new_products_values']);

    //$products['ids'] = $confg['new_products_values']['skus'];
    //$product['skus'] = $confg['new_products_values'];

    // the value for your yes/no (boolean) field
    $automatic = Mage::getStoreConfig('newproducts/new_products_values/automatic');
    $featured = Mage::getStoreConfig('newproducts/new_products_values/featured');

    var_dump($automatic);
    var_dump($featured);

    //var_dump($products);

    if($automatic == false) {
        echo "<p>Not Automatic";
       /* Product values come as skus or ids depending on
         * how they are named in the system.cfg
         */
        $newproducts = $this->getNewProductsList($config['new_products_values'], $limit, $featured);

    } else {
        /* Product values are the newest in the catalog.
         */
        $newproducts = $this->getNewProducts($limit, $featured);
    }

 

    //$newproducts = $this->getNewProducts($limit);

 ?>
<h3>New Products</h3>
<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 260px; height: 260px;">
<?php if ($newproducts->count()>0): ?>
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 260px; height: 260px;">
    <?php foreach ($newproducts as $product) : ?>
        <!-- slide -->
        <div>
            <img u="image" src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(260) ?>" alt="<?php echo $product->getName(); ?>" />
            <div u="caption" t="<?php echo $product->getName(); ?>" style="position: absolute; top: 120px; left: 0px; width: 50px;height: 50px;"><?php echo $product->getName(); ?> <?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,false); ?> <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation(' <?php echo $this->helper('checkout/cart')->getAddUrl($product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            </div>
            
        </div>
        <!-- end slide -->
    <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>
<!-- it works the same with all jquery version from 1.x to 2.x -->
<script>
    jQuery(document).ready(function ($) {
        var options = { $AutoPlay: true };
        var jssor_slider1 = new $JssorSlider$('slider1_container', options);
    });
</script>